
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALL BY COMMA DATE DIFFER END EQUAL FILTER ID LOCATION LPAREN MULTIPLY PLUS RPAREN STRING TIME\n    Program : FILTER ALL BY Predicate_list END\n    \n    Predicate_list : Predicate COMMA Predicate_list\n                   | Predicate\n    \n    Predicate  : TIME LPAREN DATE COMMA DATE RPAREN\n               | LOCATION LPAREN STRING RPAREN\n    '
    
_lr_action_items = {'FILTER':([0,],[2,]),'$end':([1,9,],[0,-1,]),'ALL':([2,],[3,]),'BY':([3,],[4,]),'TIME':([4,10,],[7,7,]),'LOCATION':([4,10,],[8,8,]),'END':([5,6,13,17,19,],[9,-3,-2,-5,-4,]),'COMMA':([6,14,17,19,],[10,16,-5,-4,]),'LPAREN':([7,8,],[11,12,]),'DATE':([11,16,],[14,18,]),'STRING':([12,],[15,]),'RPAREN':([15,18,],[17,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Program':([0,],[1,]),'Predicate_list':([4,10,],[5,13,]),'Predicate':([4,10,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> FILTER ALL BY Predicate_list END','Program',5,'p_filter','parsing.py',22),
  ('Predicate_list -> Predicate COMMA Predicate_list','Predicate_list',3,'p_predicate_list','parsing.py',33),
  ('Predicate_list -> Predicate','Predicate_list',1,'p_predicate_list','parsing.py',34),
  ('Predicate -> TIME LPAREN DATE COMMA DATE RPAREN','Predicate',6,'p_predicate','parsing.py',44),
  ('Predicate -> LOCATION LPAREN STRING RPAREN','Predicate',4,'p_predicate','parsing.py',45),
]
